config/routes.rb
Rails.application.routes.draw do

  devise_for :schools, :controllers => { :registrations => "schools/registrations", sessions: 'schools/sessions'}
  get 'specializations/index'

  mount RailsAdmin::Engine => '/interface-for-admin', as: 'rails_admin'
  devise_for :admins
  devise_for :doctors, :controllers => { :registrations => "registrations"}

   root 'home_pages#index'

   resources :doctor_clinic
   resources :appointments do
     member do
       get 'cancel_appointment'
     end
   end

   resources :doctor_specialization

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :user

  belongs_to :clinic

end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  # establish_connection(:external_db)
  # self.table_name = "doctors"

  has_many :doctor_clinic
  has_many :doctors, through: :doctor_clinic

  has_many :appointments
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :doctor_clinic
  has_many :clinics, through: :doctor_clinic

  has_many :doctor_specialization
  has_many :specializations, through: :doctor_specialization

  has_many :users, through: :appointments
  has_many :appointments
end

app/models/doctor_clinic.rb
class DoctorClinic < ActiveRecord::Base
  # establish_connection(:external_db)
   self.table_name = "doctor_clinic"

   belongs_to :clinic
   belongs_to :doctor


end

app/models/doctor_specialization.rb
class DoctorSpecialization < ActiveRecord::Base
  # establish_connection(:external_db)
   self.table_name = "doctor_specialization"

   belongs_to :specialization, foreign_key: "spec_id"
   belongs_to :doctor


end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :admins, :join_table => :admins_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/school.rb
class School < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/school_affiliation.rb
class SchoolAffiliation < ActiveRecord::Base

end

app/models/school_school_affiliation.rb
class SchoolSchoolAffiliation < ActiveRecord::Base
  self.table_name = "school_school_affiliation"
end

app/models/specialization.rb
class Specialization < ActiveRecord::Base
  # establish_connection(:external_db)
  # self.table_name = "doctors"

  has_many :doctor_specialization
  has_many :doctors, through: :doctor_specialization
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :doctors, through: :appointments
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def index
    # response = HTTParty.get("http://www.letshareit.in/uploads.json").to_json
    #
    #  @file_list = JSON.parse(response)
    #
    # puts "========================="
    #   p response
    #
    # puts "==========================="

    @doctors = Doctor.all

    @clinics = Clinic.all

    puts "================================"
      p @doctors
    puts "================================"

    @appointments = current_doctor.appointments if current_doctor
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctor_clinics_helper.rb
module DoctorClinicsHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/specializations_helper.rb
module SpecializationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home_pages/_doctor.html.erb
<div class="container-fluid">

  <div class="col-md-6">
    <div class="container">
      <h4>Add clinics to your profile <%= link_to "click here", doctor_clinic_index_path %> </h4>
      <h4>Add specializations to your profile <%= link_to "click here", doctor_specialization_index_path %> </h4>
    </div>

  </div>

  <div class="col-md-6">

    <h3>your appointment details </h3>

    <table class="table table-responsive table-hover">
      <thead>
        <tr>
          <th>Clinic</th>
          <th>Patient</th>
          <th>Appointment time</th>
          <th>Description</th>
          <th>status</th>
        </tr>
      </thead>

      <tbody>
        <% @appointments.each do |appointment| %>
          <tr>
            <td><%= appointment.clinic.name %></td>
            <td><%= appointment.name %></td>
            <td><%= appointment.appointment_time %></td>
            <td><%= appointment.description %></td>
            <% if appointment.doctor.id == current_doctor.id %>
              <% if appointment.cancel == true %>
                <td><small> cancelled </small></td>
              <% else %>
                <td><%= link_to "cancel", controller: "appointments", action: "cancel_appointment", id: appointment %></td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/home_pages/_school.html.erb
<div class="container-fluid">
  <div class="col-md-2">

  </div>

  <div class="col-md-8">
    <div class="container-fluid">
      Information about School
    </div>
  </div>

  <div class="col-md-2">

  </div>
</div>

app/views/home_pages/index.html.erb
<% if doctor_signed_in? %>
  <%= render partial: '/home_pages/doctor' %>
<% end %>

<% if admin_signed_in? %>
  Admin: <%= current_admin.email %> <br>
  <%= link_to "edit", edit_admin_registration_path %> |
  <%= link_to "sign out", destroy_admin_session_path, method: :delete %> <br>
  <a href="/interface-for-admin">GOTO admin view</a>

<% end %>


<% if school_signed_in? %>
  <%# link_to "Sign out", destroy_school_session_path, method: :delete %>
  <br>
  <%= link_to "Edit information", edit_school_registration_path %>
  <%= render partial: '/home_pages/school' %>
<% end %>

<!-- <# @file_list.each do |file| %>
  <%# file %> <br>
<%# end %> -->
<!-- List of doctors <br>
<% @doctors.each do |a| %>
  <%= a.name %> <br>
<% end %> -->