config/routes.rb
Rails.application.routes.draw do

  devise_for :schools, :controllers => { :registrations => "schools/registrations", sessions: 'schools/sessions'}
  get 'specializations/index'

  mount RailsAdmin::Engine => '/interface-for-admin', as: 'rails_admin'
  devise_for :admins
  devise_for :doctors, :controllers => { :registrations => "registrations"}

   root 'home_pages#index'

   resources :doctor_clinic
   resources :appointments do
     member do
       get 'cancel_appointment'
     end
   end

   resources :doctor_specialization

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :user

  belongs_to :clinic

end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  # establish_connection(:external_db)
  # self.table_name = "doctors"

  has_many :doctor_clinic
  has_many :doctors, through: :doctor_clinic

  has_many :appointments
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :doctor_clinic
  has_many :clinics, through: :doctor_clinic

  has_many :doctor_specialization
  has_many :specializations, through: :doctor_specialization

  has_many :users, through: :appointments
  has_many :appointments
end

app/models/doctor_clinic.rb
class DoctorClinic < ActiveRecord::Base
  # establish_connection(:external_db)
   self.table_name = "doctor_clinic"

   belongs_to :clinic
   belongs_to :doctor


end

app/models/doctor_specialization.rb
class DoctorSpecialization < ActiveRecord::Base
  # establish_connection(:external_db)
   self.table_name = "doctor_specialization"

   belongs_to :specialization, foreign_key: "spec_id"
   belongs_to :doctor


end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :admins, :join_table => :admins_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/school.rb
class School < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/school_affiliation.rb
class SchoolAffiliation < ActiveRecord::Base

end

app/models/school_school_affiliation.rb
class SchoolSchoolAffiliation < ActiveRecord::Base
  self.table_name = "school_school_affiliation"
end

app/models/specialization.rb
class Specialization < ActiveRecord::Base
  # establish_connection(:external_db)
  # self.table_name = "doctors"

  has_many :doctor_specialization
  has_many :doctors, through: :doctor_specialization
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :doctors, through: :appointments
  has_many :appointments
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctor_clinics_helper.rb
module DoctorClinicsHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/specializations_helper.rb
module SpecializationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Evolve</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
   <div class="container-fluid">
     <div class="navbar-header">
       <a class="navbar-brand" href="<%= root_path %>">Evolve</a>
     </div>
     <ul class="nav navbar-nav navbar-right">
       <% if doctor_signed_in? %>

          <li><a href="#">logged in as : <%= current_doctor.name %> (doctor) </a></li>
          <li><%= link_to "edit profile", edit_doctor_registration_path %></li>
          <li><%= link_to "sign out", destroy_doctor_session_path, method: :delete %></li>

       <% elsif admin_signed_in? %>

          <li><a href="#">logged in as : <%= current_admin.email %> (admin) </a></li>
          <li><%= link_to "sign out", destroy_admin_session_path, method: :delete %></li>

      <% elsif school_signed_in? %>
          <li><a href="#">logged in as : <%= current_school.email %> (school) </a></li>
          <li><%= link_to "sign out", destroy_school_session_path, method: :delete %></li>
      <% else %>

           <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
           <li><a href="<%= new_school_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Login as school</a></li>
           <li><a href="<%= new_doctor_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Login as doctor</a></li>
           <li><a href="<%= new_admin_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Login as Admin</a></li>

       <% end %>
     </ul>
   </div>
  </nav>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>